server:
  port: ${PORT_SERVER:9004}
---
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${KEYCLOAK_HOST:http://localhost:8080}/realms/${KEYCLOAK_REALM:vitech-shopping}/protocol/openid-connect/certs
---
spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/dev?escapeSyntaxCallMode=callIfNoReturn}
    username: ${JDBC_USERNAME:postgres}
    password: ${JDBC_PASSWORD:phale50}
---
spring:
  datasource:
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
---
spring:
  application:
    name: ${HOSTNAME:log-service}
eureka: #<1>
  instance:
    app-name: ${HOSTNAME:log-service}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
---
keycloak:
  realm-master: ${KEYCLOAK_REALM_ADMIN:master}
  realm: ${KEYCLOAK_REALM:vitech-shopping}
  auth-server-url: ${KEYCLOAK_HOST:http://localhost:8080}
  client-admin: ${KEYCLOAK_CLIENT_ADMIN:admin-cli}
  client: ${KEYCLOAK_CLIENT:vitech-shopping}
  credentials:
    client-id: admin-cli
    username: ${KEYCLOAK_USERNAME:admin}
    password: ${KEYCLOAK_PASSWORD:admin}
---
eureka:
  instance:
    ip-address: ${CLIENT_IP_ADDRESS:localhost}
    prefer-ip-address: ${PREFER_IP_ADDRESS:false}
    hostname: ${HOSTNAME:localhost}

---
spring:
  mvc:
    dispatch-options-request: true
---
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
---
spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
---
spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      key-deserializer: ${KEY_SERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
      value-deserializer: ${VALUE_SERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
      group-id: vitech-statistic
    template:
      default-topic: order-statistic